# SPDX-License-Identifier: LGPL-2.1-or-later
# Every third-party action in .github/workflows is pinned by commit, with the
# release it came from in a comment, and nothing moves a commit pin by itself.
# This proposes the move -- one grouped pull request a week -- so a pin is
# reviewed rather than forgotten. LibreSCRS/ci is pinned the same way but moved
# deliberately, every reference at one commit, together with what its profile
# for this repository expects.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
    ignore:
      - dependency-name: 'LibreSCRS/ci*'
